image:
  file: .gitpod.Dockerfile

tasks:
  - init: go mod tidy
  - command: |
      go run main.go
  - open: http://localhost:8080

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - ms-go.vscode-go
