tasks:
  - init: |
      # Update package list and install Go
      sudo apt-get update && sudo apt-get install -y golang mongodb

      # Start MongoDB service
      sudo service mongod start

      # Install Go dependencies
      go mod tidy

  - command: |
      # Start the Go application server
      go run main.go

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - ms-go.vscode-go